# Generated by Django 4.2.30 on 2026-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_manually_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
