# Generated by Django 4.2.30 on 2026-04-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_uncertain',
            field=models.BooleanField(default=False),
        ),
    ]
