# Generated by Django 4.2.30 on 2026-04-12 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_transaction_is_uncertain'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ModelTrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('trigger_source', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto'), ('SCHEDULED', 'Scheduled')], default='MANUAL', max_length=15)),
                ('corrected_samples', models.PositiveIntegerField(default=0)),
                ('training_size', models.PositiveIntegerField(default=0)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_training_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'version')},
            },
        ),
    ]
